version: '3'
services:
  dockerdemo:
    image: pranaliaws/todoapp:1.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE= TODODB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    #restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGO_DB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL= mongodb://admin:password@mongodb:27017
volumes:
  mongodb-data:
    driver: local
